using DLSS_Swapper.Data;

namespace DLSS_Swapper.Dlls;

/// <summary>
/// Everything that varies between one swappable dll type and another.
/// </summary>
/// <remarks>
/// The app used to answer each of these questions with its own switch statement, which meant adding
/// an upscaler required finding every one of them. They are gathered here so a new type is a single
/// row in <see cref="DllTypes"/>.
/// </remarks>
public sealed class DllTypeDefinition
{
    /// <summary>
    /// The asset type as stored in the database.
    /// </summary>
    /// <remarks>
    /// These values are written to the game_asset and game_history tables, so they can never be
    /// renumbered. Reordering the enum once already broke existing installs.
    /// </remarks>
    public required GameAssetType AssetType { get; init; }

    /// <summary>The type recorded for this dll's ".dlsss" backup.</summary>
    public required GameAssetType BackupAssetType { get; init; }

    /// <summary>The file we look for when scanning a game, for example "nvngx_dlss.dll".</summary>
    public required string FileName { get; init; }

    /// <summary>
    /// The key this type appears under in the downloaded manifest, for example "dlss".
    /// </summary>
    /// <remarks>
    /// The manifest is generated by a separate repository, so these are an external contract and
    /// cannot be renamed from here.
    /// </remarks>
    public required string ManifestKey { get; init; }

    public required DllVendor Vendor { get; init; }

    /// <summary>
    /// True when this type's meaningful version is the internal SDK version rather than the dll's
    /// own file version.
    /// </summary>
    /// <remarks>
    /// FSR reports both and they do not move together. FSR 3.1.4 ships as file version 1.0.1.41314
    /// while a later 3.1.2 build ships as 1.0.2.38022, so ranking by file version puts the older SDK
    /// on top. Everything else has a single version and this is false.
    /// </remarks>
    public bool VersionFromInternalName { get; init; } = false;

    /// <summary>Resource key for the translated display name.</summary>
    public required string DisplayNameResourceKey { get; init; }

    /// <summary>
    /// Whether games ship this dll themselves.
    /// </summary>
    /// <remarks>
    /// True for every released upscaler: the copy found in a game folder on first scan is the one
    /// the developer shipped, which is precisely why it is worth saving before anything overwrites
    /// it.
    ///
    /// False for a dll no game ships. A copy of one in a game folder was put there by a person or a
    /// tool, so there is no original to save and never will be — and saving one anyway fabricates
    /// an "original" that is really just the injected file, which the app would then offer to
    /// restore and count as protection it does not have. It also costs a full second copy on disk,
    /// which for a 158 MB dll across a library is most of a gigabyte.
    /// </remarks>
    public bool GamesShipThisDll { get; init; } = true;

    /// <summary>
    /// Whether the upstream manifest is expected to carry a key for this type.
    /// </summary>
    /// <remarks>
    /// True for everything the manifest builder produces, and a test holds the manifest to it, so a
    /// key renamed upstream is caught here rather than by versions silently vanishing from the app.
    ///
    /// False for a type this fork recognises that upstream has no key for — an unreleased dll, say.
    /// Such a type has no download source and its versions can only ever arrive by importing the
    /// file, which the picker and the upscalers page handle already. Setting the flag rather than
    /// adding the key to the shipped manifest is deliberate: both manifest copies are overwritten
    /// wholesale from upstream by sync_manifest.ps1, so an invented key there survives exactly
    /// until the next sync and then fails the very test it was added to satisfy.
    /// </remarks>
    public bool ExpectedInUpstreamManifest { get; init; } = true;
}
