using DLSS_Swapper.Data;

namespace DLSS_Swapper.Dlls;

/// <summary>
/// Everything that varies between one swappable dll type and another.
/// </summary>
/// <remarks>
/// The app used to answer each of these questions with its own switch statement, which meant adding
/// an upscaler required finding every one of them. They are gathered here so a new type is a single
/// row in <see cref="DllTypes"/>.
/// </remarks>
public sealed class DllTypeDefinition
{
    /// <summary>
    /// The asset type as stored in the database.
    /// </summary>
    /// <remarks>
    /// These values are written to the game_asset and game_history tables, so they can never be
    /// renumbered. Reordering the enum once already broke existing installs.
    /// </remarks>
    public required GameAssetType AssetType { get; init; }

    /// <summary>The type recorded for this dll's ".dlsss" backup.</summary>
    public required GameAssetType BackupAssetType { get; init; }

    /// <summary>The file we look for when scanning a game, for example "nvngx_dlss.dll".</summary>
    public required string FileName { get; init; }

    /// <summary>
    /// The key this type appears under in the downloaded manifest, for example "dlss".
    /// </summary>
    /// <remarks>
    /// The manifest is generated by a separate repository, so these are an external contract and
    /// cannot be renamed from here.
    /// </remarks>
    public required string ManifestKey { get; init; }

    public required DllVendor Vendor { get; init; }

    /// <summary>Resource key for the translated display name.</summary>
    public required string DisplayNameResourceKey { get; init; }
}
