<#
.SYNOPSIS
    Pulls the dll manifest from the builder repository and says what changed.

.DESCRIPTION
    The list of swappable dlls is generated by a separate repository
    (beeradmoore/dlss-swapper-manifest-builder) and this repo carries a copy of it in two places:
    src/Assets/static_manifest.json, which ships inside the app and is what a first run or an
    offline run reads, and docs/manifest.json, which is the copy a Pages site would serve.

    A running app already re-fetches the live manifest hourly, so new *versions* reach users
    without anything here happening. What does not reach them is a new dll *type*: an unrecognised
    manifest key is kept verbatim by DllKeyedRecordsJson.ReadProperty so that saving an imported
    manifest cannot corrupt it, which means the app carries it silently and offers it to nobody.
    That is the case this script exists for, and the reason it reports new types separately from
    new versions rather than printing one undifferentiated diff.

.NOTES
    The registry keys are read out of DllTypes.cs rather than listed here, so there is no second
    copy of them to fall out of date. The authoritative check is
    DllTypesTests.EveryPopulatedManifestKey_IsHandledByTheRegistry, which uses the real registry
    and runs in CI; this is the early warning that puts the answer in a pull request body. If the
    two ever disagree, the test is right.
#>
[CmdletBinding()]
param(
    # The builder repo's output. Deliberately the raw file rather than the Pages copy the app
    # reads: Pages lags a build behind, and this wants the newest answer.
    [string] $ManifestUrl = 'https://raw.githubusercontent.com/beeradmoore/dlss-swapper-manifest-builder/refs/heads/main/manifest.json',

    # Where to write the markdown report. Optional; it always goes to stdout as well.
    [string] $SummaryPath,

    # Report what would change without writing either copy.
    [switch] $CheckOnly
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$repoRoot = Split-Path -Parent $PSScriptRoot
$staticManifestPath = Join-Path $repoRoot 'src/Assets/static_manifest.json'
$docsManifestPath = Join-Path $repoRoot 'docs/manifest.json'
$dllTypesPath = Join-Path $repoRoot 'core/DLSS.Swapper.Core/Dlls/DllTypes.cs'

# The manifest's one property that is not a dll type.
$knownDllsKey = 'known_dlls'

function Get-RegistryManifestKey {
    param([string] $Path)

    if (-not (Test-Path -LiteralPath $Path)) {
        throw "Could not find the dll registry at $Path."
    }

    $source = Get-Content -LiteralPath $Path -Raw
    $matched = [regex]::Matches($source, 'ManifestKey\s*=\s*"([^"]+)"')

    if ($matched.Count -eq 0) {
        throw "Found no ManifestKey entries in $Path. The registry's shape has changed and this script needs updating."
    }

    return @($matched | ForEach-Object { $_.Groups[1].Value })
}

# A record's identity. md5_hash is per file and unique across the manifest, so it survives a
# version string being relabelled; the version is only ever what gets displayed.
function Get-RecordKey {
    param($Record)

    if ($Record.PSObject.Properties.Name -contains 'md5_hash' -and $Record.md5_hash) {
        return $Record.md5_hash
    }

    return $Record.version
}

function Get-RecordLabel {
    param($Record)

    $label = $Record.version

    if ($Record.PSObject.Properties.Name -contains 'additional_label' -and $Record.additional_label) {
        $label = "$label ($($Record.additional_label))"
    }

    if ($Record.PSObject.Properties.Name -contains 'is_dev_file' -and $Record.is_dev_file) {
        $label = "$label [dev]"
    }

    return $label
}

function Get-DllKey {
    param($Manifest)

    return @($Manifest.PSObject.Properties.Name | Where-Object { $_ -ne $knownDllsKey })
}

# Every key with something under it, from the records at the top level and from the known dll
# hashes, which are keyed the same way. Both are read because a type can appear in one before the
# other: the hashes of a dll games ship with are knowable before there is anything to download.
function Get-PopulatedKey {
    param($Manifest)

    $keys = [System.Collections.Generic.List[string]]::new()

    foreach ($name in Get-DllKey $Manifest) {
        if (@($Manifest.$name).Count -gt 0) {
            $keys.Add($name)
        }
    }

    if ($Manifest.PSObject.Properties.Name -contains $knownDllsKey -and $null -ne $Manifest.$knownDllsKey) {
        foreach ($property in $Manifest.$knownDllsKey.PSObject.Properties) {
            if (@($property.Value).Count -gt 0) {
                $keys.Add($property.Name)
            }
        }
    }

    return @($keys | Select-Object -Unique)
}

Write-Host "Fetching $ManifestUrl"

# Written as raw bytes rather than parsed and re-serialised, so the committed file stays
# byte-for-byte what the builder published and the diff only ever shows real changes.
$response = Invoke-WebRequest -Uri $ManifestUrl -UseBasicParsing
$newBytes = $response.Content
if ($newBytes -is [string]) {
    $newBytes = [System.Text.Encoding]::UTF8.GetBytes($newBytes)
}

$newText = [System.Text.Encoding]::UTF8.GetString($newBytes).TrimStart([char]0xFEFF)
$newManifest = $newText | ConvertFrom-Json

$oldManifest = $null
if (Test-Path -LiteralPath $staticManifestPath) {
    $oldManifest = Get-Content -LiteralPath $staticManifestPath -Raw | ConvertFrom-Json
}

$registryKeys = Get-RegistryManifestKey -Path $dllTypesPath
Write-Host "The registry knows $($registryKeys.Count) dll types: $($registryKeys -join ', ')"

# --- New dll types, the case that needs code --------------------------------------------------

$newTypes = @(Get-PopulatedKey $newManifest | Where-Object { $registryKeys -notcontains $_ })

# --- Version changes, per type ----------------------------------------------------------------

$versionChanges = [System.Collections.Generic.List[object]]::new()

foreach ($key in Get-DllKey $newManifest) {
    $newRecords = @($newManifest.$key)

    $oldRecords = @()
    if ($null -ne $oldManifest -and $oldManifest.PSObject.Properties.Name -contains $key) {
        $oldRecords = @($oldManifest.$key)
    }

    $oldKeys = @($oldRecords | ForEach-Object { Get-RecordKey $_ })
    $newKeys = @($newRecords | ForEach-Object { Get-RecordKey $_ })

    $added = @($newRecords | Where-Object { $oldKeys -notcontains (Get-RecordKey $_) })
    $removed = @($oldRecords | Where-Object { $newKeys -notcontains (Get-RecordKey $_) })

    if ($added.Count -gt 0 -or $removed.Count -gt 0) {
        $versionChanges.Add([pscustomobject]@{
            Key = $key
            Added = @($added | ForEach-Object { Get-RecordLabel $_ })
            Removed = @($removed | ForEach-Object { Get-RecordLabel $_ })
        })
    }
}

# --- Known dll hash counts ---------------------------------------------------------------------

$hashChanges = [System.Collections.Generic.List[object]]::new()

if ($newManifest.PSObject.Properties.Name -contains $knownDllsKey) {
    foreach ($property in $newManifest.$knownDllsKey.PSObject.Properties) {
        $newCount = @($property.Value).Count

        $oldCount = 0
        if ($null -ne $oldManifest -and
            $oldManifest.PSObject.Properties.Name -contains $knownDllsKey -and
            $oldManifest.$knownDllsKey.PSObject.Properties.Name -contains $property.Name) {
            $oldCount = @($oldManifest.$knownDllsKey.$($property.Name)).Count
        }

        if ($newCount -ne $oldCount) {
            $hashChanges.Add([pscustomobject]@{
                Key = $property.Name
                Old = $oldCount
                New = $newCount
            })
        }
    }
}

# --- The report ----------------------------------------------------------------------------------

$report = [System.Collections.Generic.List[string]]::new()

if ($newTypes.Count -gt 0) {
    $report.Add('## A new dll type needs adding')
    $report.Add('')
    $report.Add('The manifest carries entries under keys the app has no row for. Everything under them is')
    $report.Add('invisible in the app until one is added, and nothing at runtime reports that:')
    $report.Add('')
    foreach ($type in $newTypes) {
        $report.Add("- ``$type``")
    }
    $report.Add('')
    $report.Add('Each needs a `DllTypeDefinition` in `core/DLSS.Swapper.Core/Dlls/DllTypes.cs` — asset type,')
    $report.Add('backup asset type, file name, manifest key, vendor and a display name resource key — plus that')
    $report.Add('string in `src/Translations/en-US/Resources.resw`. `DllTypesTests` stays red until then.')
    $report.Add('')
}

if ($versionChanges.Count -gt 0) {
    $report.Add('## New versions')
    $report.Add('')
    foreach ($change in $versionChanges) {
        $report.Add("### ``$($change.Key)``")
        foreach ($item in $change.Added) {
            $report.Add("- Added $item")
        }
        foreach ($item in $change.Removed) {
            $report.Add("- Removed $item")
        }
        $report.Add('')
    }
}

if ($hashChanges.Count -gt 0) {
    $report.Add('## Known dll hashes')
    $report.Add('')
    $report.Add('Hashes of dlls games are known to ship with, which is what identifies an unswapped file.')
    $report.Add('')
    foreach ($change in $hashChanges) {
        $report.Add("- ``$($change.Key)``: $($change.Old) to $($change.New)")
    }
    $report.Add('')
}

if ($report.Count -eq 0) {
    $report.Add('No change. The manifest matches the copy already committed.')
    $report.Add('')
}

$reportText = $report -join "`n"

Write-Host ''
Write-Host $reportText

if ($SummaryPath) {
    Set-Content -LiteralPath $SummaryPath -Value $reportText -Encoding utf8
    Write-Host "Wrote the report to $SummaryPath"
}

if ($CheckOnly) {
    Write-Host 'Check only, so neither copy was written.'
    return
}

[System.IO.File]::WriteAllBytes($staticManifestPath, $newBytes)
[System.IO.File]::WriteAllBytes($docsManifestPath, $newBytes)

Write-Host "Wrote $staticManifestPath"
Write-Host "Wrote $docsManifestPath"
